# Use the official Node.js image as a base
FROM node:18 AS development

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ../ .

# Expose the port for the React app
EXPOSE 4000

# Set environment variable for React to use polling for file changes
ENV CHOKIDAR_USEPOLLING=true

# Start the React app in development mode
CMD ["npm", "start"]
